import = [
    "~/.config/alacritty/themes/themes/everforest_dark.toml"
]

[window]
# startup_mode = "Maximized"
#decorations = "None"

[font]
size = 14

[font.normal]
family = "FiraCode Nerd Font Mono"
style = "Regular"
